### ISSUE TITLE
Looking for an example of building a MDP using ExactSparseMatrix

### ISSUE THREAD

**Issue by oyendrila-dobe** [stormchecker/stormpy#28]
Will it be possible to provide a small example of how to build a MDP using rational transition values? I'm not sure how to generate the transition value as expected while building the ExactSparseMatrix.

**Comment by volkm** [comment]
I added a small tests for the `ExactSparseMatrixBuilder` [here](https://github.com/moves-rwth/stormpy/blob/master/tests/storage/test_matrix_builder.py#L37). Generating an exact transition value is done by using `stormpy.Rational` as datatype. You can create a rational number from either integers (and then performing the division by yourself) or by parsing a string.
Note that `stormpy.Rational(1/2)` will not give you the desired result, because stormpy creates the rational number from the floating point number 1/2 (which is already imprecise).

**Comment by oyendrila-dobe** [comment]
This example no longer seems to work.
I re-installed stormpy 1.6.3 yesterday and am trying to create exact MDPs. Here's a screenshot of the first few steps I am using to build an ExactSparseMatrix. 

![Screen Shot 2022-10-06 at 1 17 41 PM](https://user-images.githubusercontent.com/14862450/194377566-ebd8a2a4-e547-4362-954c-61d8a3ad8baa.png)

However, I get the error below 

![Screen Shot 2022-10-06 at 1 30 02 PM](https://user-images.githubusercontent.com/14862450/194379855-cb99cc63-d1e1-4a89-9eb0-386947625703.png)

Was there any change in the representation of fractions? I did try with a specific value like 1/6, but the error still persists. 
Interestingly, the docker for stormpy does not give this error with the same code and input file.

**Comment by volkm** [comment]
It seems to me that there is some misconfiguration in your local installation. In principle your code should work. I tested it on my machine and it runs successfully.
If possible, I would recommend to update both Storm and stormpy to the latest version 1.7.0 (and also pycarl). That way we are sure all updates are present.
Maybe also check whether the tests of stormpy run successfully. This might already indicate some problems.

**Comment by oyendrila-dobe** [comment]
You are right, rebuilding the library solved it. But even after providing an explicit path for storm, [this line](https://github.com/moves-rwth/stormpy/blob/f19e657eec9cbb439a6934a3ea78a13cdba26d97/setup.py#L67) does not utilize the specified folder. I had to unlink it forcibly in my cmake folder. is there a specific reason for the check in [this line](https://github.com/moves-rwth/stormpy/blob/f19e657eec9cbb439a6934a3ea78a13cdba26d97/setup.py#L72)?

**Comment by sjunges** [comment]
Yes, so that line is necessary because  https://github.com/moves-rwth/stormpy/blob/f19e657eec9cbb439a6934a3ea78a13cdba26d97/setup.py#L64 may sometimes not be honored (mostly because people may give a wrong path there...) and this was more stable. 

However, I think that in this line https://github.com/moves-rwth/stormpy/blob/f19e657eec9cbb439a6934a3ea78a13cdba26d97/cmake/CMakeLists.txt#L3 storm_dir should be explicitly passed to find library....

**Comment by sjunges** [comment]
Reading this: https://cmake.org/cmake/help/latest/command/find_package.html#id6 we should add HINTS ${storm_DIR} to that line. @oyendrila-dobe if you are in the position to try that, that would be very helpful!

(We later also may want to pass the version to the search)....

**Comment by oyendrila-dobe** [comment]
I actually cannot, as I deleted the previous storm version. I will update here if I come across a similar situation soon.

**Comment by volkm** [comment]
Added as a separate issue in https://github.com/moves-rwth/stormpy/issues/102.

The original problem with the ExactSparseMatrix is fixed.
