### ISSUE TITLE
Total Expected Reward - MDP

### ISSUE THREAD

**Issue by cazevedo** [stormchecker/stormpy#6]
Hello,

I'm using stormpy to minimize/maximize the total expected reward for a very simple mdp (7 states).
For that I'm encoding the mdp as a prism file and I'm using the methods **parse_prism_program** and **parse_properties_for_prism_program** to parse the model and the properties, respectively.
I'm using the following prism formula to state the objective that I'm trying to minimize:
```
formula = 'Rmin=? [ C ]'
```
Everything works perfectly, but, the results outputed by the **model_checking** method only provide values for 4 states, instead of providing for all 7 states. The reason for this, seems to be that, the method only performs value iteration over the states reachable from the initial state, and, in my case, only 3 other states are present in all the possible paths from the initial state, despite having a total of 7 states. Is this true, or is there something that I'm not performing correctly?

If yes, then, is there any way to obtain the value for all states of a given mdp, when trying to minimize/maximize the total expected reward? And if that is possible how can I know the mapping between the outputed values and the states of the inputed model?

Thank you very much!

**Comment by tquatmann** [comment]
Is it possible to send the prism file to us? You can either post its contents here or send it to us via mail at storm-dev@i2.informatik.rwth-aachen.de
The expected behavior should be that only the states reachable from the initial state(s) are explored. Depending on some settings, you should get a result either just for the initial state or for all (reachable) states. It seems that _something_ is broken here.
Towards your second question: The C++ core of Storm is able to generate a mapping from state valuation (i.e., variable assignment) to state index. We need to check whether it is possible to use this functionality with the python api.

**Comment by sjunges** [comment]
> The reason for this, seems to be that, the method only performs value iteration over the states reachable from the initial state,

This is true and the behaviour that PRISM and Storm adapt. You may want to work around this by making all states initial, but that will yield a (possibly drastic) performance hit for Storm. 

Regarding the state valuation, there is a little bit of code missing. I am willing to add that for you. 
Nevertheless, I wonder whether you really want to build from a PRISM file then, because this extra labelling induces quite some overhead, and if you keep being interested in such small MCs, then using an explicit input format might be a suitable and easier alternative.

**Comment by cazevedo** [comment]
Thanks for the quick reply.
I'm currently testing with a 7 state MDP, but only for debugging purposes, since I intend to use it to solve bigger MDP's (thousand of states). Nevertheless, you can find below the file I'm using:
[example_mdp_prism.txt](https://github.com/moves-rwth/stormpy/files/3566299/example_mdp_prism.txt)

I tried your suggestion and set all states as initial states, and in fact, I am able to get the value for all states at the expense of longer computation time.

I don't necessarily need to build the PRISM file, I'm willing to use any other input format as long as is faster and usable from Python. What is this more explicit input that you recommend?

I followed [this](https://moves-rwth.github.io/stormpy/doc/parametric_models.html) part of the documentation to obtain the results. What am I missing?

**Comment by sjunges** [comment]
Hi,

sorry, I just realised that we never replied to this issue (due to holidays). Can we still help you?
