### ISSUE TITLE
StormPy build fails

### ISSUE THREAD

**Issue by oyendrila-dobe** [stormchecker/stormpy#7]
I'm trying to install stormpy on an ubuntu 19.06 docker. I have all the prerequisites satisfied, namely, carl, carl-parser, pycarl, and storm. Initially, I thought it was a memory issue. Hence I increased it from 2gb to 4gb. However, the error still persists. Please find the error screenshot attached below. 

<img width="1437" alt="Screen Shot 2019-09-24 at 4 31 12 PM" src="https://user-images.githubusercontent.com/14862450/65552135-3b96de00-dee9-11e9-9d99-2ad9eba6b428.png">

**Comment by oyendrila-dobe** [comment]
I'm guessing that had to do with the correct version of Z3. However, now I'm getting several warnings for Py_DEPRECATED(3.7). And finally, the make fails. Find the error messages below. 
<img width="1440" alt="Screen Shot 2019-09-24 at 8 36 00 PM" src="https://user-images.githubusercontent.com/14862450/65562181-fbe0ee00-df0a-11e9-994d-2c3546d90064.png">
<img width="1437" alt="Screen Shot 2019-09-24 at 8 37 01 PM" src="https://user-images.githubusercontent.com/14862450/65562210-1adf8000-df0b-11e9-8fcc-fb83d9e3c7fc.png">

**Comment by volkm** [comment]
First of all, compiling stormpy can use quite some memory. Increasing the available memory - as you did - helps in these cases. Another possibility is to disable multithreaded compilation and only use one thread. This can be achieved by providing the flag `--jobs 1` (see https://moves-rwth.github.io/stormpy/installation.html#optional-build-arguments).

Second, we are aware of the deprecation warnings of pybind11, but switching to a newer version requires a lot of work by us. For the moment you can ignore those warnings as they are not relevant for the success of the compilation.

Last, the missing `computeAllUntilProbabilities` is unfortunately due to incompatibilities between your Storm and stormpy version. The stable branch of Storm currently does not work with the master branch of stormpy. For the moment, I recommend to use the master branch of Storm which works with the master branch of stormpy.

We are planning to release a new Storm version in the next couple of days. You can also wait for this new release which again is compatible with stormpy.
One last thing: we also already provide a Docker container for Storm (https://hub.docker.com/r/movesrwth/storm/). We are also planning to provide a Docker container for Stormpy including all its dependencies (Carl, Storm, pycarl) with the new Storm release. This Docker container then saves you the trouble of manually building everything by yourself.

**Comment by oyendrila-dobe** [comment]
Thanks, for the quick reply. The master branch solution was still throwing errors but the ```--job 1``` solved the issue. I wanted to create my own docker to install a lot of dependencies for prophesy, hence didn't prefer the storm docker.
Looking forward to working with the upcoming releases.
